services:
  db:
    image: postgis/postgis:18-3.6
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql
    # don't expose data base to the host
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d landslides"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - landslides-net

  # run migrations and import data; exits when done
  importer:
    build: .
    env_file: .env
    # override POSTGRES_HOST to point to the 'db' service in this compose file
    environment:
      - POSTGRES_HOST=db
    
    # set --dump-layers if individual processed source files should be written;
    # files are written to `./data/processed-layers`
    command: bash -c "alembic upgrade head && python scripts/import.py --no-dump-layers"
    volumes:
      - ./data:/app/data
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./scripts:/app/scripts

    depends_on:
      db:
        condition: service_healthy
    networks:
      - landslides-net
    
  api:
    image: pramsey/pg_tileserv:20250131
    restart: unless-stopped
    env_file: .env
    environment:
      # point to the 'db' service as host
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/landslides
    # For web deployment: Do not expose port to host
    # ports:
    #   - "7800:7800"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - landslides-net
      - web  # external network for connection with other services

networks:
  landslides-net:
    driver: bridge
  web:
    external: true
